-- dw_materialized_views.general_ledger_line_item_error source

CREATE MATERIALIZED VIEW dw_materialized_views.general_ledger_line_item_error
BACKUP NO
DISTSTYLE KEY DISTKEY(table_name)
SORTKEY(original_cycle_date, original_batch_id, error_classification_name)
AS
SELECT
	recorded_timestamp,
	original_cycle_date,
	original_batch_id,
	original_recorded_timestamp,
	CAST(split_part(table_name, '_', 1) AS varchar(50)) AS source_system_name,
	table_name,
	error_classification_name,
	error_message,
	error_record_aging_days,
	reprocess_flag,
	error_json.source_system_nm,
	error_json.ledger_name,
	error_json.subledger_short_name,
	error_json.event_type_code,
	error_json.transaction_date,
	error_json.gl_reversal_date,
	error_json.gl_application_area_code,
	error_json.gl_source_code,
	error_json.secondary_ledger_code,
	error_json.data_type,
	error_json.default_currency,
	error_json.default_amount,
	error_json.debit_credit_indicator,
	error_json.orig_gl_source_document_id,
	error_json.orig_gl_company,
	error_json.orig_gl_account,
	error_json.orig_gl_center,
	error_json.orig_gl_description_1,
	error_json.orig_gl_description_2,
	error_json.orig_gl_description_3,
	error_json.orig_gl_project_code,
	error_json.groupcontractnumber,
	error_json.contractnumber,
	error_json.contractsourcesystemname,
	error_json.contractstatuscode,
	error_json.contractissueage,
	error_json.statutoryresidentstatecode,
	error_json.sourcesystemactivitytypedescription,
	error_json.activitydepositsourcebatchidentifier,
	error_json.activityreversalcode,
	error_json.activitysourceclaimidentifier,
	error_json.activitysourceoriginatinguserid,
	error_json.activitysourcetransactioncode,
	error_json.activitywithholdingtaxjurisdiction,
	error_json.activitywithholdingtaxjurisdictioncountrycode,
	error_json.checknumber,
	error_json.contractissuedate,
	error_json.contractissuestatecode,
	error_json.contractsourcemarketingorganizationcode,
	error_json.plancode,
	error_json.reinsuranceassumedcededflag,
	error_json.reinsurancecounterpartyreportinggroup,
	error_json.reinsurancecounterpartytype,
	error_json.reinsurancetreatybasis,
	error_json.reinsurancetreatyname,
	error_json.sourceagentidentifier,
	error_json.reinsuranceaccountflag,
	error_json.sourcefundidentifier,
	error_json.sourcesystemgeneralledgeraccountnumber,
	error_json.sourcesystemgroupcontractnumber,
	error_json.sourcesystemreinsurancecounterpartycode,
	error_json.line_description,
	error_json.investmentportfoliocode,
	error_json.instrumentcode,
	error_json.assetclasscode,
	error_json.activitytypegroup,
	error_json.activitytype,
	error_json.activityamounttype,
	error_json.contractadministrationlocationcode,
	error_json.contractsourceaccountingcenterdeviator,
	error_json.contracteffectivedate,
	error_json.contractdurationinyears,
	error_json.contractbillingmode,
	error_json.contractgroupindicator,
	error_json.contractmodelpremium,
	error_json.contractproductfundmortalityandexpensecode,
	error_json.contractproducttypecode,
	error_json.payoutoptionindicator,
	error_json.activitysourceaccountingememcode,
	error_json.activitysourceaccountingdeviator,
	error_json.activityaccountingbalanceentryindicator,
	error_json.activityeffectivedate,
	error_json.activitymoneyethodcode,
	error_json.distributionreasoncode,
	error_json.fundclassindicator,
	error_json.fundnumber,
	error_json.fundunits,
	error_json."1035exchangeindicator",
	error_json.primaryinsuredprimarypostalcode,
	error_json.primaryannuitantnonresidentaliantaxstatus,
	error_json.ownernonresidentaliantaxstatus,
	error_json.sourcelegalentitycode,
	error_json.cessionidentifier,
	error_json.contractparticipationindicator,
	error_json.sourceaccountingid,
	error_json.majorlineofbusiness,
	error_json.claimsproductidentifier,
	error_json.managementcode,
	error_json.src_desc,
	error_json as error_record
FROM (
	SELECT *,
		json_parse(error_record) as error_json
	FROM financedwcurated.curated_error
	WHERE reprocess_flag in ('Y', 'N')
		AND table_name like '%general_ledger_line_item%'
);

