-- erpdw_views.general_ledger_line_item source

CREATE OR REPLACE VIEW erpdw_views.general_ledger_line_item AS
SELECT
	activity_accounting_id
	,transaction_number
	,line_number
	,sourceaccountingid
	,default_currency
	,default_amount
	,debit_credit_indicator
	,gl_full_source_code
	,orig_gl_source_document_id
	,orig_gl_company
	,orig_gl_account
	,orig_gl_center
	,orig_gl_description_1
	,orig_gl_description_2
	,orig_gl_description_3
	,orig_gl_project_code
	,groupcontractnumber
	,contractnumber
	,contractsourcesystemname
	,contractstatuscode
	,ifrs17cohort
	,ifrs17grouping
	,ifrs17measurementmodel
	,ifrs17portfolio
	,ifrs17profitability
	,ifrs17reportingcashflowtype
	,sourcesystemactivitytypedescription
	,statutoryresidentcountrycode
	,statutoryresidentstatecode
	,activitydepositsourcebatchidentifier
	,activityreversalcode
	,activitysourceclaimidentifier
	,activitysourceoriginatinguserid
	,activitysourcetransactionid
	,activitywithholdingtaxjurisdiction
	,activitywithholdingtaxjurisdictioncountrycode
	,checknumber
	,contractissuedate
	,contractissuestatecode
	,contractsourceorganizationcode
	,plancode
	,reinsuranceassumedcededflag
	,reinsurancecounterpartyreportinggroup
	,reinsurancecounterpartytype
	,reinsurancetreatybasis
	,reinsurancetreatyname
	,sourceagentidentifier
	,sourcefundidentifier
	,sourcesystemgeneralledgeraccountnumber
	,sourcesystemgroupcontractnumber
	,sourcesystemreinsurancecounterpartycode
	,line_description
	,source_system_name
	,cycledate
	,batchid
	,original_cycle_date
	,original_batch_id
	,inserttimestamp
	,updatetimestamp
	,investmentportfoliocode
	,instrumentcode
	,assetclasscode
	,activitytypegroup
	,activitytype
	,activityamounttype
	,contractadministrationlocationcode
	,contractsourceaccountingcenterdeviator
	,contracteffectivedate
	,contractdurationinyears
	,contractbillingmode
	,contractgroupindicator
	,contractmodelpremium
	,contractproductfundmortalityandexpensecode
	,contractproducttypecode
	,payoutoptionindicator
	,activitysourceaccountingememcode
	,activitysourceaccountingdeviator
	,activityaccountingbalanceentryindicator
	,activityeffectivedate
	,activitymoneyethodcode
	,distributionreasoncode
	,fundclassindicator
	,fundnumber
	,fundunits
	,"1035exchangeindicator"
	,icginputflag
	,modifiedcompanyentryflag
	,primaryinsuredprimarypostalcode
	,primaryannuitantnonresidentaliantaxstatus
	,ownernonresidentaliantaxstatus
	,sourcelegalentitycode
	,cessionidentifier
	,contractparticipationindicator
	,transactionclass
	,transactionrideritype
	,transactionchargetype
	,transactionfeetype
	,transactiontaxtype
	,contractissueage
	,reinsuranceaccountflag
	,reinsurancegroupindividualflag
	,typeofbusinessreinsured
	,reinsurancetreatycomponentidentifier
	,reinsurancemultiplier
	,treatyruleset
	,majorlineofbusiness
	,claimsproductidentifier
	,managementcode
from
	erpdw.general_ledger_line_item
WITH NO SCHEMA BINDING;

