CREATE TABLE IF NOT EXISTS financedwcontrols.control_results
(
    control_results_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,inserttimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,updatetimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,control_load_date DATE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,start_dt DATE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,end_dt DATE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,batch_id BIGINT NOT NULL
    ,cycle_date DATE NOT NULL
    ,"domain" VARCHAR(100) NOT NULL
    ,hop_name VARCHAR(255)
    ,sys_nm VARCHAR(50) NOT NULL
    ,measure_table VARCHAR(255) NOT NULL
    ,measure_field VARCHAR(255) NOT NULL
    ,measure_name VARCHAR(50) NOT NULL
    ,feed_id VARCHAR(255)
    ,src_control_log_id BIGINT
    ,src_adj_control_log_id BIGINT
    ,src_ignore_control_log_id BIGINT
    ,tgt_control_log_id BIGINT
    ,tgt_adj_control_log_id BIGINT
    ,tgt_ignore_control_log_id BIGINT
    ,module_name VARCHAR(100)
    ,measure_group VARCHAR(100)
    ,src_measure_value DECIMAL(38,10)
    ,src_adj_measure_value DECIMAL(38,10)
    ,src_ignore_measure_value DECIMAL(38,10)
    ,tgt_measure_value DECIMAL(38,10)
    ,tgt_adj_measure_value DECIMAL(38,10)
    ,tgt_ignore_measure_value DECIMAL(38,10)
    ,variance DECIMAL(38,10)
    ,is_match CHAR(1) NOT NULL
    ,load_status VARCHAR(50)
    ,duration VARCHAR(255)
    ,control_result_description VARCHAR(255)
    ,UNIQUE (batch_id, cycle_date, sys_nm, measure_table, measure_name, feed_id, measure_group)
    ,FOREIGN KEY (domain) REFERENCES financedorchestration.hash_definition(domain_name)
    ,FOREIGN KEY (src_control_log_id) REFERENCES financedwcontrols.controllogging(control_log_id)
    ,FOREIGN KEY (tgt_control_log_id) REFERENCES financedwcontrols.controllogging(control_log_id)
    ,FOREIGN KEY (src_adj_control_log_id) REFERENCES financedwcontrols.controllogging(control_log_id)
    ,FOREIGN KEY (tgt_adj_control_log_id) REFERENCES financedwcontrols.controllogging(control_log_id)
    ,FOREIGN KEY (src_ignore_control_log_id) REFERENCES financedwcontrols.controllogging(control_log_id)
    ,FOREIGN KEY (tgt_ignore_control_log_id) REFERENCES financedwcontrols.controllogging(control_log_id)
);
