CREATE TABLE IF NOT EXISTS financedwcontrols.controllogging
(
    control_log_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,recorded_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,inserttimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,updatetimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,batch_id BIGINT NOT NULL
    ,cycle_date DATE NOT NULL
    ,"domain" VARCHAR(100) NOT NULL
    ,hop_name VARCHAR(255)
    ,p_sys_nm VARCHAR(50) NOT NULL
    ,sys_nm VARCHAR(100) NOT NULL
    ,measure_table VARCHAR(255) NOT NULL
    ,measure_table_description VARCHAR(255)
    ,measure_field VARCHAR(50) NOT NULL
    ,measure_name VARCHAR(255) NOT NULL
    ,measure_src_tgt_add_indicator VARCHAR(2) NOT NULL
    ,feed_id VARCHAR(255)
    ,measure_value DECIMAL(38,10) NOT NULL
    ,measure_value_datatype VARCHAR(50) NOT NULL
    ,measure_group VARCHAR(100)
    ,module_name VARCHAR(100)
    ,measure_category VARCHAR(255)
    ,start_dt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,end_dt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,duration VARCHAR(255)
    ,load_catg VARCHAR(255)
    ,load_status VARCHAR(50)
    ,measure_job_name VARCHAR(100)
    ,application_id VARCHAR(255)
    ,measure_note VARCHAR(255)
    ,FOREIGN KEY (domain) REFERENCES financedorchestration.hash_definition(domain_name)
    ,UNIQUE (batch_id, cycle_date, sys_nm, "domain", hop_name, measure_table, measure_field, measure_name, measure_src_tgt_add_indicator, feed_id, measure_group, measure_category)
);
