CREATE TABLE IF NOT EXISTS erpdw.general_ledger_line_item
(
 batchid INTEGER NOT NULL
 ,cycledate DATE NOT NULL
 ,source_system_name VARCHAR(50) NOT NULL
 ,inserttimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
 ,updatetimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
 ,original_cycle_date DATE
 ,original_batch_id INTEGER
 ,activity_accounting_id CHAR(30) PRIMARY KEY NOT NULL
 ,transaction_number VARCHAR(50) NOT NULL
 ,line_number INT NOT NULL
 ,default_currency VARCHAR(100)
 ,default_amount decimal(18,2) NOT NULL
 ,debit_credit_indicator VARCHAR(100)
 ,gl_full_source_code VARCHAR(30)
 ,orig_gl_source_document_id VARCHAR(100)
 ,orig_gl_company VARCHAR(30)
 ,orig_gl_account VARCHAR(30)
 ,orig_gl_center VARCHAR(30)
 ,orig_gl_description_1 VARCHAR(30)
 ,orig_gl_description_2 VARCHAR(30)
 ,orig_gl_description_3 VARCHAR(30)
 ,groupcontractnumber VARCHAR(15)
 ,contractnumber VARCHAR(15)
 ,contractsourcesystemname VARCHAR(30)
 ,ifrs17cohort VARCHAR(100)
 ,ifrs17grouping VARCHAR(100)
 ,ifrs17measurementmodel VARCHAR(30)
 ,ifrs17portfolio VARCHAR(100)
 ,ifrs17profitability VARCHAR(100)
 ,ifrs17reportingcashflowtype VARCHAR(30)
 ,sourcesystemactivitydescription VARCHAR(30)
 ,statutoryresidentcountrycode VARCHAR(5)
 ,statutoryresidentstatecode VARCHAR(5)
 ,statutorysourcesubobjectidentifier VARCHAR(20)
 ,activityreversalcode VARCHAR(1)
 ,activitysourcelegalidentifier VARCHAR(255)
 ,activitysourceaccountinginterfaceid VARCHAR(50)
 ,activitysourcetransactioncode VARCHAR(50)
 ,activitywithholdingtaxjurisdictioncountrycode VARCHAR(30)
 ,checknumber VARCHAR(25)
 ,contractissuedate Date
 ,contractissuestatecode VARCHAR(5)
 ,contractsourceaccountingorganizationcode VARCHAR(20)
 ,reinsuranceassumedcededflag VARCHAR(30)
 ,reinsurancecounterpartytype VARCHAR(30)
 ,reinsurancetreatybasis VARCHAR(30)
 ,reinsurancetreatynumber VARCHAR(30)
 ,sourceagentidentifier VARCHAR(255)
 ,sourcefundidentifier VARCHAR(255)
 ,sourcesystemgeneralledgeraccountnumber VARCHAR(30)
 ,sourcesystemgroupcontractnumber VARCHAR(30)
 ,reinsurancecounterpartyreportinggroup VARCHAR(30)
 ,line_description VARCHAR(1000)
 ,investmentportfolioode VARCHAR(100)
 ,instrumentcode VARCHAR(100)
 ,assetclasscode VARCHAR(20)
 ,sourceacctunitgid VARCHAR(255)
 ,contractstatuscode VARCHAR(30)
 ,activitytypegroup VARCHAR(50)
 ,activityamounttype VARCHAR(255)
 ,contractadministrationlocationcode VARCHAR(10)
 ,contractsourceaccountingcenterdeviator VARCHAR(5)
 ,contracteffectivedate DATE
 ,contractdurationinyears INTEGER
 ,contractbillingmode VARCHAR(255)
 ,contractgroupindicator VARCHAR(1)
 ,contractmodelpremium NUMERIC(18,6)
 ,contractproductfundmortalityandexpensecode VARCHAR(255)
 ,contractproducttypecode VARCHAR(255)
 ,contractproductvariantcode VARCHAR(255)
 ,activitysourceaccountingdeviator VARCHAR(5)
 ,activitysourceaccountingbalancedentryindicator VARCHAR(1)
 ,activityeffectivedate DATE
 ,activitymovementmethodcode VARCHAR(255)
 ,distributionreasoncode VARCHAR(5)
 ,fundclassificationindicator VARCHAR(1)
 ,fundnumber VARCHAR(50)
 ,fundunits NUMERIC(18,6)
 ,"1035exchangeindicator" VARCHAR(1)
 ,iceinputflag VARCHAR(1)
 ,modifiedcompanyflag VARCHAR(1)
 ,primaryinsuredprimarypostalcode VARCHAR(15)
 ,primaryannuitantnonresidentalienstatus VARCHAR(255)
 ,owneroneresidentalienstatus VARCHAR(255)
 ,sourcelegalentitycode VARCHAR(10)
 ,cessionidentifier VARCHAR(30)
 ,contractparticipationindicator VARCHAR(30)
 ,transactionclass VARCHAR(255)
 ,transactionliordertype VARCHAR(255)
 ,transactionchargeType VARCHAR(255)
 ,transactionfeetype VARCHAR(255)
 ,transactiontaxType VARCHAR(255)
 ,contractissuage INT
 ,reinsuranceaccountflag VARCHAR(30)
 ,reinsurancegroupindividualflag VARCHAR(30)
 ,typeofbusinessreinsured VARCHAR(30)
 ,reinsurancetreatycomponentidentifier VARCHAR(30)
 ,reinsurancemultiplier VARCHAR(30)
 ,reinsurancetreatyresult VARCHAR(30)
 ,majorlineofbusiness VARCHAR(100)
 ,claimsproductidentifier VARCHAR(100)
 ,unmanagedcode VARCHAR(255)
 ,UNIQUE (cycledate, batchid, source_system_name, transaction_number, line_number)
 ,FOREIGN KEY (transaction_number) REFERENCES erpdw.general_ledger_header(transaction_number)
)
DISTSTYLE KEY
DISTKEY (transaction_number)
SORTKEY (
 cycledate, source_system_name
);
