CREATE TABLE IF NOT EXISTS financedwcontrols.kc2_controllogging
(
    control_log_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,inserttimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,updatetimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,load_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,batch_id BIGINT NOT NULL
    ,cycle_date DATE NOT NULL
    ,source_system_name VARCHAR(50) NOT NULL
    ,"domain" VARCHAR(100) NOT NULL
    ,hop_name VARCHAR(50) NOT NULL
    ,control_id VARCHAR(100) NOT NULL
    ,fact_col_name VARCHAR(100)
    ,group_col_name VARCHAR(MAX)
    ,group_col_val VARCHAR(MAX)
    ,operation VARCHAR(50) NOT NULL
    ,fact_val VARCHAR(50) NOT NULL
    ,FOREIGN KEY (domain) REFERENCES financedorchestration.hash_definition(domain_name)
    ,UNIQUE (batch_id, cycle_date, source_system_name, "domain", hop_name, fact_col_name, group_col_name, group_col_val)
    ,UNIQUE (batch_id, cycle_date, source_system_name, control_id, hop_name, group_col_val)
);
