CREATE TABLE IF NOT EXISTS financedwcontrols.lkup_kc2_control_measures
(
    measure_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,source_system_name VARCHAR(50) NOT NULL
    ,domain_name VARCHAR(100) NOT NULL
    ,measure_type VARCHAR(50) NOT NULL
    ,measure_field VARCHAR(MAX) NOT NULL
    ,key_control_type VARCHAR(50) NOT NULL
    ,reconciliation_indicator CHAR(1) NOT NULL
    ,is_active CHAR(1) NOT NULL
    ,inserttimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,updatetimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,FOREIGN KEY (domain_name) REFERENCES financedorchestration.hash_definition(domain_name)
    ,UNIQUE (key_control_type, source_system_name, domain_name, measure_type, measure_field)
);
