CREATE TABLE IF NOT EXISTS financedwcontrols.lkup_control_definition
(
    control_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,source_system_name VARCHAR(50)
    ,control_name VARCHAR(100) NOT NULL
    ,control_category VARCHAR(100) NOT NULL
    ,control_type VARCHAR(100) NOT NULL
    ,control_value VARCHAR(100)
    ,control_value2 VARCHAR(100)
    ,control_value_datatype VARCHAR(100)
    ,control_value_datatype2 VARCHAR(100)
    ,control_note VARCHAR(100)
    ,control_comparison_operator VARCHAR(100)
    ,control_critical VARCHAR(100) NOT NULL
    ,inserttimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,updatetimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,UNIQUE (source_system_name, control_name, control_category, control_type)
);
