CREATE TABLE IF NOT EXISTS financedwcontrols.lkup_control_measures
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,"domain" VARCHAR(100) NOT NULL
    ,sys_nm VARCHAR(50) NOT NULL
    ,measure_name VARCHAR(50) NOT NULL
    ,measure_table VARCHAR(255) NOT NULL
    ,measure_field VARCHAR(255) NOT NULL
    ,measure_value_datatype VARCHAR(50) NOT NULL
    ,measure_src_tgt_add_indicator CHAR(1) NOT NULL
    ,operation_type VARCHAR(100) NOT NULL
    ,inserttimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,updatetimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'US/Central')
    ,FOREIGN KEY (domain) REFERENCES financedorchestration.hash_definition(domain_name)
    ,UNIQUE ("domain", sys_nm, measure_name, measure_table, measure_field, measure_src_tgt_add_indicator)
);
